language: ruby
rvm:
  - 2.2.5

install:
  - gem install html-proofer

script:
  - htmlproofer --check-external-hash --check-html --check-favicon --check-img-http --check-opengraph --enforce-https --timeframe 6w static

cache:
  directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer # https://github.com/gjtorikian/html-proofer/issues/381

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
